fb/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout  # 利用內建的view funciton

#from django.conf import settings
urlpatterns = [
    url(r'^accounts/login/$', views.user_login, name='login'),
    url(r'^$', views.index, name="index"),
    url(r'^accounts/logout/$', views.logout, name="logout"),
    url(r'^addschoolclass/$', views.addschoolclass, name="addschoolclass"),
    url(r'^deleteschoolclass/(?P<id>\d+)/$',
        views.deleteschoolclass, name="deleteschoolclass"),
    url(r'^classparent/(?P<id>\d+)/',
        views.classparent, name="classparent"),
    url(r'^addclassparent/$', views.addclassparent, name="addclassparent"),
    url(r'deleteclasstu/(?P<id>\d+)/(?P<vpk>\d+)/$',
        views.deleteclasstu, name="deleteclasstu"),
    url(r'^ebook/', views.ebook, name='ebook'),
    url(r'^addebook/$', views.addebook, name="addebook"),
    url(r'^deletebook/(?P<id>\d+)/$',
        views.deletebook, name="deletebook"),
    url(r'^addebookdetail/(?P<id>\d+)/$',
        views.addebookimage, name="addebookdetail"),
    url(r'^contactindex/', views.contactindex, name="contactindex"),
    url(r'^addcontact/(?P<id>\d+)/$', views.addcontact, name="contactindex"),
    url(r'deletecontact/(?P<id>\d+)/(?P<vpk>\d+)/$',
        views.deletecontact, name="deletecontact"),
    url(r'^adddailyrecord/$', views.adddailyrecord, name="adddailyrecord"),
    url(r'^deletedailyrecord/(?P<id>\d+)/$', views.deletedailyrecord, name="deletedailyrecord"),
    url(r'^addannounce/', views.addannounce, name="addannounce"),
    url(r'^deleteannounce/(?P<id>\d+)/$', views.deleteannounce, name="deleteannounce"),


    
    
]

fb/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator

# Create your models here.


class Schoolclass(models.Model):
    user = models.ForeignKey(User, related_name="schoolclass")
    schoolclass = models.CharField("班級名稱", max_length=200)
    year = models.CharField("年度與班級編號", max_length=100)

    def __unicode__(self):
        return self.schoolclass


class Studentinformation(models.Model):
    contact = models.ForeignKey(Schoolclass, related_name="studentInfor")
    email = models.EmailField("家長連絡登入帳戶")
    name = models.CharField("家長姓名", max_length=255)
    childName = models.CharField("小朋友姓名", max_length=255)
    phone = models.CharField("家長聯絡電話(手機)", max_length=10, validators=[
                             MinLengthValidator(9)])
    useraddress = models.CharField("家庭住址", max_length=255, blank=True)
    usercontact = models.CharField("家長與孩童關係", max_length=255, blank=True)

    def __unicode__(self):
        return self.childName


class Ebook(models.Model):
    user = models.ForeignKey(User, related_name="ebook")
    title = models.CharField("標題", max_length=255)
    image = models.ImageField("電子書封面", upload_to='ebookcovers/')

    def __unicode__(self):
        return self.title


class Ebook_detail(models.Model):
    contact = models.ForeignKey(Ebook, related_name="ebookdetail")
    image = models.ImageField('電子書圖片', upload_to='profiles/', blank=True)
    sortbynumber = models.AutoField(primary_key=True)

    def __unicode__(self):
        return self.contact


class Contactbook2(models.Model):
    contact = models.ForeignKey(Schoolclass, related_name="contactbook2")
    title = models.CharField("聯絡簿標題", max_length=255)
    content = models.CharField("細項內容", max_length=255)
    honor = models.CharField("表彰名單", max_length=255)
    datetime = models.DateTimeField(auto_now=True)
    imagecontact = models.ImageField(upload_to="contactbook/", blank=True)

    def __unicode__(self):
        return self.title


class Contacturl(models.Model):
    contact = models.ForeignKey(Contactbook2, related_name="contacturl")
    url = models.CharField("傳送url", max_length=255, blank=True)

    def __unicode__(self):
        return self.url


class Dailyrecord(models.Model):
    contact = models.ForeignKey(User, related_name="dailyrecord")
    datetime = models.DateField("日期", auto_now=True)
    topic = models.CharField("教學單元", max_length=255)
    studentnum = models.CharField("學生人數", max_length=255)
    attend = models.CharField("出席人數", max_length=255)
    absence = models.CharField("缺席人數", max_length=255)
    title = models.CharField("教學日誌標題", max_length=255)
    event = models.CharField("偶發事件處理事項", max_length=2550)
    content = models.TextField("教學內容", max_length=2550)
    introspective = models.TextField("教學省思", max_length=2550)
    image = models.ImageField("教學日誌圖片", upload_to="dailyrecord/", blank=True)

    def __unicode__(self):
        return self.topic


class Announcement(models.Model):
    user = models.ForeignKey(User, related_name="announce")
    datetime = models.CharField("公告時間",max_length=255)
    title = models.CharField("公告標題", max_length=255)
    content = models.CharField("公告內容", max_length=2550)
    file = models.FileField("上傳檔案", upload_to="announce/", blank=True)

    def __unicode__(self):
        return self.title

templates/announcement_index.html
<html lang="en">

<head>
    {%load static%}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <title>幼兒園聯絡簿</title>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <!-- Bootstrap core CSS -->
    <link href="{%static "css/bootstrap.css "%}" rel="stylesheet">
    <!--external css-->
    <link href="{%static "font-awesome/css/font-awesome.css "%}" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{%static "css/zabuto_calendar.css "%}">
    <link rel="stylesheet" type="text/css" href="{%static "js/gritter/css/jquery.gritter.css "%}"/>
    <link rel="stylesheet" type="text/css" href="{%static "lineicons/style.css "%}">
    <link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/smoothness/jquery-ui.css" />
    <!-- Custom styles for this template -->
    <link href="{%static "css/style.css "%}" rel="stylesheet">
    <link href="{%static "css/style-responsive.css "%}" rel="stylesheet">
    <script src="{%static "js/chart-master/Chart.js "%}"></script>
    <style type="text/css">
        p{font-size: 20px;}
    </style>
</head>

<body>
    <section id="container">
    {%block content%}
        <!-- **********************************************************************************************************************************************************
      TOP BAR CONTENT & NOTIFICATIONS
      *********************************************************************************************************************************************************** -->
        <!--header start-->
        <header class="header black-bg">
            <div class="sidebar-toggle-box">
                <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
            </div>
            <!--logo start-->
            <a href="index.html" class="logo"><b>幼兒園聯絡簿</b></a>
            <!--logo end-->
            <div class="nav notify-row" id="top_menu">
                <!--  notification start -->
                <!--  notification end -->
            </div>
            <div class="top-menu">
                <ul class="nav pull-right top-menu">
                    <li><a class="logout" href="/accounts/logout/">Logout</a></li>
                </ul>
            </div>
        </header>
        <!--header end-->
        <!-- **********************************************************************************************************************************************************
      MAIN SIDEBAR MENU
      *********************************************************************************************************************************************************** -->
        <!--sidebar start-->
       <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion">
                    <h5 class="centered" style="margin-bottom: 0px;" val="{{user.email}}">{{user.email}}</h5>
                    <li class="mt" >
                        <a class="" href="/index">
                            <i class="fa fa-dashboard"></i>
                            <span>新增班級以及學生資料</span>
                        </a>
                    </li>
                    <li>
                        <a class="" href="/ebook">
                            <i class="fa fa-dashboard"></i>
                            <span>新增電子書資料</span>
                        </a>
                    </li>
                    <li>
                      <a class="" href="/contactindex">
                            <i class="fa fa-dashboard"></i>
                            <span>新增聯絡簿資料</span>
                        </a>
                    </li>
                    <li>
                      <a class="" href="/adddailyrecord">
                            <i class="fa fa-dashboard"></i>
                            <span>新增教師日誌資料</span>
                        </a>
                    </li>
                    <li>
                      <a class="" href="/addannounce">
                            <i class="fa fa-dashboard"></i>
                            <span>新增校園公告</span>
                        </a>
                    </li>
                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sideba
        <!--sidebar end-->
        <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->
        <!--main content start-->

        <section id="main-content">
            <section class="wrapper">
            <div class="row mt">
                <div class="col-lg-12">
                  <div class="form-panel" style="font-size: 18px; font-weight: 700;">
                      <h4 class="mb" value=""><i class="fa fa-angle-right"></i>
                      校園公告資料</h4>
                      <form  enctype="multipart/form-data" class="form-horizontal style-form" id="postannounceform">
                        {% csrf_token %}
                        <div class="form-group">
                              <label class="col-sm-2 col-sm-2 control-label">新增公告標題：</label>
                              <div class="col-sm-10">
                                  <input type="text"  class="form-control" name="title" id="id_title">
                              </div>
                          </div>
                        <div class="form-group">
                            <label class="col-sm-2 col-sm-2 control-label">新增公告時間：</label>
                            <div class="col-sm-6">
                              <input type="text" id="id_datetime" name="datetime" >
                            </div>
                          </div>
                          <div class="form-group">
                              <label class="col-sm-2 col-sm-2 control-label">新增公告內容：</label>
                              <div class="col-sm-10">
                                  <textarea name="content" cols="40" rows="5" id="id_content"></textarea>
                              </div>
                          </div>
                          <div class="form-group">
                              <label class="col-sm-2 col-sm-2 control-label">新增班級名稱：</label>
                              <div class="col-sm-10">
                                  <input id="id_file" name="file" type="file">
                              </div>
                          </div>
                        <button type="button" name="imageupload" class="btn btn-danger" id="dangerbutton">新增資料</button>
                        <button type="button" class="btn btn-info">回上頁</button>
                      </form>
                  </div>
                </div><!-- col-lg-12-->         
            </div><!-- /row -->
            <div class="row mt">
                  <div class="col-md-12">
                      <div class="content-panel">
                          <table class="table table-striped table-advance table-hover">
                              <h4><i class="fa fa-angle-right"></i>已送出資料</h4>
                              <hr>
                              <thead>
                              <tr>
                                  <th>公告時間</th>
                                  <th>公告標題</th>
                                  <th>公告內容</th>
                                  <th>檔案</th>
                                  <th></th>
                              </tr>
                              </thead>
                              <tbody>
                              {%for an in announce%}
                                <tr>
                                  <td>{{an.datetime}}</td>
                                  <td>{{an.title}}</td>
                                  <td>{{an.content}}</td>
                                  {%if an.file%}
                                  <td><a href="{{an.file.url}}">下載檔案</a></td>
                                  {%endif%}
                                  <td><a class="btn btn-danger btn-xs" id="" href="/deleteannounce/{{an.id}}"><i class="fa fa-trash-o"></i></a></td>
                                
                                </tr>
                              {%endfor%}
                              </tbody>
                          </table>
                      </div><!-- /content-panel -->
                  </div><!-- /col-md-12 -->
              </div><!-- /row -->
            </section>
        </section>
    </section>
    <script src="{%static "js/jquery.js "%}"></script>
    <script src="{%static "js/jquery-1.8.3.min.js "%}"></script>
    <script src="{%static "js/bootstrap.min.js "%}"></script>
    <script class="include" type="text/javascript" src="{%static "js/jquery.dcjqaccordion.2.7.js "%}"></script>
    <script src="{%static "js/jquery.scrollTo.min.js "%}"></script>
    <script src="{%static "js/jquery.nicescroll.js "%}" type="text/javascript"></script>
    <script src="{%static "js/jquery.sparkline.js "%}"></script>
    <!--common script for all pages-->
    <script src="{%static "js/common-scripts.js "%}"></script>
    <script type="text/javascript" src="{%static "js/gritter/js/jquery.gritter.js "%}"></script>
    <script type="text/javascript" src="{%static "js/gritter-conf.js "%}"></script>
    <!--script for this page-->
    <script src="{%static "js/sparkline-chart.js "%}"></script>
    <script src="{%static "js/zabuto_calendar.js "%}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script src="https://www.gstatic.com/firebasejs/4.1.2/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/4.1.2/firebase-auth.js"></script>
    <script src="https://www.gstatic.com/firebasejs/4.1.2/firebase-database.js"></script>
    <script src="https://www.gstatic.com/firebasejs/4.1.2/firebase-messaging.js"></script>
    <script src="https://www.gstatic.com/firebasejs/4.1.2/firebase.js">
    </script>
    <script type="text/javascript">
      $(function(){
        $('#id_datetime').datepicker({
            dateFormat: 'yy-mm-dd'
        });
      });
    </script>
     <script>
        // Initialize Firebase
        var config = {
            apiKey: "AIzaSyAZqDKfA9ikHD-tVtDQbf3Zl0xbEJqWHsc",
            authDomain: "androidpackages-e5a5c.firebaseapp.com",
            databaseURL: "https://androidpackages-e5a5c.firebaseio.com",
            projectId: "androidpackages-e5a5c",
            storageBucket: "androidpackages-e5a5c.appspot.com",
            messagingSenderId: "298309886865"
        };
        firebase.initializeApp(config);
    </script>
   
  <script type="text/javascript">
document.getElementById('dangerbutton').addEventListener('click',function(){
      var x = document.getElementById("id_file");
      uploadImageAsPromise(x.files[0]);
      var n=x.files.length;
      var myForm=document.getElementById('postannounceform');
      formData=new FormData(myForm);
      $.ajax({
              type:'POST',
              url:'/addannounce/',
              data:formData,
              cache: false,
              contentType: false,
              processData: false,
              async: false,
              success:function(){
              
              }
        });
  });
  function uploadImageAsPromise (imageFile) {
    return new Promise(function (resolve, reject) {
        var storageRef = firebase.storage().ref('announce/'+imageFile.name);
        //Upload file
        var task = storageRef.put(imageFile);

        //Update progress bar
        task.on('state_changed',
            function progress(snapshot){

            },
            function error(err){

            },
            function complete(){
                var storageRef = firebase.storage().ref('Announce/'+imageFile.name);
                var downloadURL = task.snapshot.downloadURL;
                var updates={};
                var title=$('#id_title').val();
                var postData={
                  file:downloadURL,
                  title:$('#id_title').val(),
                  content:$('#id_content').val(),
                  datetime:$('#id_datetime').val(),
                  user:'{{user.email}}',
              };
               updates['announce/'+title]=postData;
                firebase.database().ref().update(updates);
                document.getElementById('postannounceform').reset();
              setTimeout(location.reload.bind(location), 3000);
            }
        );
    });
  };

  </script>

  {%endblock%}
</body>

</html>

templates/dailyrecord_index.html
<!DOCTYPE html>
<html lang="en">

<head>
    {%load static%}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Dashboard">
    <meta name="keyword" content="Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <title>幼兒園聯絡簿</title>
    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
    <!-- Bootstrap core CSS -->
    <link href="{%static "css/bootstrap.css "%}" rel="stylesheet">
    <!--external css-->
    <link href="{%static "font-awesome/css/font-awesome.css "%}" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{%static "css/zabuto_calendar.css "%}">
    <link rel="stylesheet" type="text/css" href="{%static "js/gritter/css/jquery.gritter.css "%}"/>
    <link rel="stylesheet" type="text/css" href="{%static "lineicons/style.css "%}">
    <!-- Custom styles for this template -->
    <link href="{%static "css/style.css "%}" rel="stylesheet">
    <link href="{%static "css/style-responsive.css "%}" rel="stylesheet">
    <script src="{%static "js/chart-master/Chart.js "%}"></script>
    <style type="text/css">
        p{font-size: 20px;}
    </style>
</head>

<body>
    <section id="container">
    {%block content%}
        <!-- **********************************************************************************************************************************************************
      TOP BAR CONTENT & NOTIFICATIONS
      *********************************************************************************************************************************************************** -->
        <!--header start-->
        <header class="header black-bg">
            <div class="sidebar-toggle-box">
                <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
            </div>
            <!--logo start-->
            <a href="index.html" class="logo"><b>幼兒園聯絡簿</b></a>
            <!--logo end-->
            <div class="nav notify-row" id="top_menu">
                <!--  notification start -->
                <!--  notification end -->
            </div>
            <div class="top-menu">
                <ul class="nav pull-right top-menu">
                    <li><a class="logout" href="/accounts/logout/">Logout</a></li>
                </ul>
            </div>
        </header>
        <!--header end-->
        <!-- **********************************************************************************************************************************************************
      MAIN SIDEBAR MENU
      *********************************************************************************************************************************************************** -->
        <!--sidebar start-->
       <aside>
            <div id="sidebar" class="nav-collapse ">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion">
                    <h5 class="centered" style="margin-bottom: 0px;" val="{{user.email}}">{{user.email}}</h5>
                    <li class="mt" >
                        <a class="" href="/index">
                            <i class="fa fa-dashboard"></i>
                            <span>新增班級以及學生資料</span>
                        </a>
                    </li>
                    <li>
                        <a class="" href="/ebook">
                            <i class="fa fa-dashboard"></i>
                            <span>新增電子書資料</span>
                        </a>
                    </li>
                    <li>
                      <a class="" href="/contactindex">
                            <i class="fa fa-dashboard"></i>
                            <span>新增聯絡簿資料</span>
                        </a>
                    </li>
                    <li>
                      <a class="" href="/adddailyrecord">
                            <i class="fa fa-dashboard"></i>
                            <span>新增教師日誌資料</span>
                        </a>
                    </li>
                    <li>
                      <a class="" href="/addannounce">
                            <i class="fa fa-dashboard"></i>
                            <span>新增校園公告</span>
                        </a>
                    </li>
                  
                    
                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sideba
        <!--sidebar end-->
        <!-- **********************************************************************************************************************************************************
      MAIN CONTENT
      *********************************************************************************************************************************************************** -->
        <!--main content start-->

        <section id="main-content">
            <section class="wrapper">
            <div class="row mt">
                <div class="col-lg-12">
                  <div class="form-panel" style="font-size: 18px; font-weight: 700;">

                      <h4 class="mb" value=""><i class="fa fa-angle-right"></i>
                      教師日誌資料新增</h4>
                      <form class="form-horizontal style-form" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                          <div class="form-group">
                              <label class="col-sm-3 col-sm-3 control-label">新增教學日誌標題：</label>
                              <div class="col-sm-9">
                                  <input id="id_title" name="title" type="text">
                              </div>
                          </div>
                          <div class="form-group">
                              <label class="col-sm-3 col-sm-3 control-label">新增學生人數：</label>
                              <div class="col-sm-9">
                                  <input id="id_studentnum" name="studentnum" type="text">
                              </div>
                          </div>
                          <div class="form-group">
                              <label class="col-sm-3 col-sm-3 control-label">新增出席人數：</label>
                              <div class="col-sm-9">
                                  <input id="id_attend" name="attend" type="text">
                              </div>
                          </div>
                          <div class="form-group">
                              <label class="col-sm-3 col-sm-3 control-label">新增缺席人數：</label>
                              <div class="col-sm-9">
                                  <input id="id_absence" name="absence" type="text">
                              </div>
                          </div>
                          <div class="form-group">
                              <label class="col-sm-3 col-sm-3 control-label">新增教學單元：</label>
                              <div class="col-sm-9">
                                  <input id="id_topic" name="topic" type="text">
                              </div>
                          </div>
                           <div class="form-group">
                              <label class="col-sm-3 col-sm-3 control-label">新增教師日誌內容：</label>
                              <div class="col-sm-9">
                                  <textarea name="content" cols="40" rows="5" id="id_content"></textarea>
                              </div>
                          </div>
                          <div class="form-group">
                              <label class="col-sm-3 col-sm-3 control-label">新增教學省思：</label>
                              <div class="col-sm-9">
                                  <textarea name="introspective" cols="40" rows="5" id="id_introspective"></textarea>
                              </div>
                          </div>
                          <div class="form-group">
                              <label class="col-sm-3 col-sm-3 control-label">新增偶發事件處理事項：</label>
                              <div class="col-sm-9">
                                  <textarea name="event" cols="40" rows="5" id="id_event"></textarea>
                              </div>
                          </div>
                           <div class="form-group">
                              <label class="col-sm-3 col-sm-3 control-label">新增教師日誌圖片：</label>
                              <div class="col-sm-9">
                                  <input id="id_image" name="image" type="file">
                              </div>
                          </div>
                          
                          <button type="submit" id="btnaddclass" class="btn btn-success ">新增教師日誌資料</button>
                           <a href="/contactindex"><button type="button" class="btn btn-info ">回上頁</button></a>
                      </form>
                  </div>
                </div><!-- col-lg-12-->         
            </div><!-- /row -->
            <div class="row mt">
                  <div class="col-md-12">
                      <div class="content-panel">
                          <table class="table table-striped table-advance table-hover">
                              <h4><i class="fa fa-angle-right"></i>已送出資料</h4>
                              <hr>
                              <thead>
                              <tr>
                                  <th>教師日誌抬頭</th>
                                  <th>教師日誌內容</th>
                                  <th>教師日誌圖片</th>
                                  <th>時間</th>
                                  <th></th>
                              </tr>
                              </thead>
                              <tbody>
                              {%for record in record%}
                              <tr>
                                <td>{{record.title}}</td>
                                <td>{{record.content}}</td>
                                <td>
                                {%if record.image%}
                                <img src="{{record.image.url}}" style="width: 200px; height: 100px;">
                                {%endif%}
                                </td>
                                <td>{{record.datetime}}</td>
                                <td><a class="btn btn-danger btn-xs" id="" href="/deletedailyrecord/{{record.id}}/"><i class="fa fa-trash-o"></i></a></td>
                              </tr>
                              {%endfor%}
                              </tbody>
                          </table>
                      </div><!-- /content-panel -->
                  </div><!-- /col-md-12 -->
              </div><!-- /row -->
            </section>
        </section>
    </section>
    <script src="{%static "js/jquery.js "%}"></script>
    <script src="{%static "js/jquery-1.8.3.min.js "%}"></script>
    <script src="{%static "js/bootstrap.min.js "%}"></script>
    <script class="include" type="text/javascript" src="{%static "js/jquery.dcjqaccordion.2.7.js "%}"></script>
    <script src="{%static "js/jquery.scrollTo.min.js "%}"></script>
    <script src="{%static "js/jquery.nicescroll.js "%}" type="text/javascript"></script>
    <script src="{%static "js/jquery.sparkline.js "%}"></script>
    <!--common script for all pages-->
    <script src="{%static "js/common-scripts.js "%}"></script>
    <script type="text/javascript" src="{%static "js/gritter/js/jquery.gritter.js "%}"></script>
    <script type="text/javascript" src="{%static "js/gritter-conf.js "%}"></script>
    <!--script for this page-->
    <script src="{%static "js/sparkline-chart.js "%}"></script>
    <script src="{%static "js/zabuto_calendar.js "%}"></script>
    
   
        
    </script>
    
    {%endblock%}
</body>

</html>